name: Push Kaggle Kernel

on:
  schedule:
    - cron: "30 4 * * *"    # 06:30 España (UTC+2)
    - cron: "30 16 * * *"   # 18:30 España (UTC+2)
  workflow_dispatch:

jobs:
  push-kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Kaggle CLI
        run: |
          pip install kaggle

      - name: Configure Kaggle credentials
        run: |
          mkdir -p ~/.config/kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json

      - name: Push Kaggle Kernel
        run: |
          kaggle kernels push -p my_kernel
